### ISSUE TITLE
Always return Did Receive Fault

### ISSUE THREAD

**Issue by papianh** [dreampowder/strava_flutter#101]
I'd like to make an example to access to the Strava data.
My manifest like this:
```
<intent-filter>
                <action android:name="android.intent.action.VIEW" />  
                <category android:name="android.intent.category.DEFAULT" /> 
                <category android:name="android.intent.category.BROWSABLE" /> 
                <data android:scheme="stravaflutter" android:host="redirect" />  
            </intent-filter>
```
I also changed the Autho Callback Domain to "redirect".
App run very smothly from begin. then Click to Login with Strava (Strava was installed with my account), then it showed second screen to click Authorize button with some scopes. But when i click Authorize button, it doesnot come back to main app (still stay at the second screen (returned example buttons/Access Token still blank). And when i changed to main app by myself (i tap on it), it showed Error Msg: Did Receive Fault. Message: PlatformException(CANCELLED, User cancelled login, null, null).

What can i do from here?
Thank you so much for your effort.
The Anh

**Comment by cpc6128** [comment]
@papianh ,
Here is the solution I found : 
https://github.com/dreampowder/strava_flutter/issues/87#issuecomment-1561629323
