### ISSUE TITLE
`type 'Null' is not a subtype of type 'FutureOr<String>'`

### ISSUE THREAD

**Issue by CoopahLimited** [dreampowder/strava_flutter#105]
there is unhandled error in repository_authentication_impl on line 126.

`completer.complete(code);` is throwing error

`type 'Null' is not a subtype of type 'FutureOr<String>'`
 
<img width="953" alt="Screenshot 2024-08-14 at 5 37 49 PM" src="https://github.com/user-attachments/assets/a9f57b61-4d9c-4411-882c-46442c89ac3c">

**Comment by dreampowder** [comment]
i guess this issue has been fixed as the authentication flow has been updated
