### ISSUE TITLE
Flutter Web Authentication Error

### ISSUE THREAD

**Issue by Parsons-David** [dreampowder/strava_flutter#19]
Device:
 - MacOS Catalina (10.15.1)
 - Chrome Browser

This is the Service library we've written:

**StravaService**
```dart
import 'package:eat/secret.dart';
import 'package:strava_flutter/Models/detailedAthlete.dart';
import 'package:strava_flutter/Models/stats.dart';
import 'package:strava_flutter/strava.dart';

class StravaService {

  static final Strava _strava = Strava(
      true,
      stravaClientSecret
  );

  static Future<int> getRunMileage() async {
    bool isAuthOk = await _strava.oauth(
        stravaClientId,
        'activity:read_all,profile:read_all',
        stravaClientSecret,
        'auto'
    );
    if (isAuthOk) {
      DetailedAthlete athlete = await _strava.getLoggedInAthlete();
      int aid = athlete.id;
      Stats stats = await _strava.getStats(aid);
      return stats.ytdRunTotals.distance;
    }
    return -1;
  }

}
```

When the code runs we see the following error in the application tab's console

![image](https://user-images.githubusercontent.com/20645441/72767438-d1a1f300-3bc1-11ea-9935-f83371fee7f5.png)

In a new tab the authorization redirect occurs:

![image](https://user-images.githubusercontent.com/20645441/72767461-f4340c00-3bc1-11ea-9499-22bc03eea48d.png)

And in that tabs console we see these errors:

![image](https://user-images.githubusercontent.com/20645441/72767513-2a718b80-3bc2-11ea-9252-5cf79bec5cd6.png)

_It's worth noting this exact service code works perfect on Mobile after configuring the `AndroidManifest.xml` & `info.plist`.

After these errors are thrown the logic fails before the `isAuthOk` conditional

**Comment by BirdyF** [comment]
Hi @Parsons-David 

Thanks for bringing this issue. In fact, I did not know that strava_flutter could run on web until I saw the tag at the top of the package page!
I suspect it is related to closeWebView.
I will do some tests on a web app and will let you know

**Comment by BirdyF** [comment]
I have done some tests localhost web using Chrome 79.0.3935 on Catalina 10.15.2 , clicking on segments and I have been a bit further than you. I have not seen the closeWebView error.

But the next problem is that I use the lib uni_links and this lib is not supporting yet web.
See [https://github.com/avioli/uni_links/issues/51](url).

So I think that the redirect page should be handled differently when running on web.
I will check what I can do and will let you know.

**Comment by Parsons-David** [comment]
Awesome, thanks for the quick response! Let me know if there's anything I can do to help!

**Comment by BirdyF** [comment]
Hi @Parsons-David 
A quick update to let you know that I worked on this issue, done some progress but still one problem that I hope to fix soon.
One question: Do you plan to have one Strava app (with only one https://www.strava.com/settings/api page) for mobile and web?

**Comment by Parsons-David** [comment]
That's the target state, but if there's a temp/faster solution that can be implemented in another way I'd be happy to try it!

**Comment by BirdyF** [comment]
Hi @Parsons-David ,

I pushed a new version (1.2.0+42) on github (not on pub.dev). BUT unfortunately it is stil not working for the web.
FYI, this version is working unchanged on Android and iOS. 
The problem on web is that when auth is requested a new tab created but when auth is done the redirection is not working properly and the example runs in this new tab. 
So you end up having two tabs with example.
I suspect that this is problem is related to a wrong redirect url.
I will let you know when I find a solution.

**Comment by BirdyF** [comment]
Hi @Parsons-David 
Have you found a solution to this issue?
I have tested with the latest version  url_launcher (5.4.5) and still found the problem (after authentication another app is created in anothe tab).

**Comment by Parsons-David** [comment]
> Hi @Parsons-David
> Have you found a solution to this issue?
> I have tested with the latest version url_launcher (5.4.5) and still found the problem (after authentication another app is created in anothe tab).

I just decided to stop supporting the web interface for my application, since I was able to support all my current users without it. I'm eventually hoping to add the web support back, but for now I don't need it.

Because of this I haven't done any further investigation into the issue.

**Comment by MrCsabaToth** [comment]
@Parsons-David just an idea, a thing to rule out: do you happen to use any adblockers?

**Comment by BirdyF** [comment]
Hi @MrCsabaToth 

I am not using adblockers and found the same problem.
In fact you can get the same problem when authenticating to Spotify.
I assume that for Flutter web, another lib than url_launcher should be used
