### ISSUE TITLE
Authorization with custom url scheme is not possible

### ISSUE THREAD

**Issue by etabakov** [dreampowder/strava_flutter#33]
Currently, authorization in a mobile application with url scheme different than 'stravaflutter' is not possible.

https://github.com/BirdyF/strava_flutter/blob/709b0af68f0e58846178c48c4282ee7bfaf62201/lib/API/constants.dart#L14-L16

Maybe, it's a good idea to parametrize this, so others schemes are also possible. I'll be happy to work on a PR if you think this is a good idea.

**Comment by BirdyF** [comment]
Hi @etabakov,
Sorry I am not sure to understand the problem. 
What is the issue to have "stravaflutter" (or even before "strava" url scheme and why you will need to change it?

**Comment by etabakov** [comment]
The biggest problem especially with the "strava" url scheme is that "strava" is used by the real Strava application. So, if a user has my app and the Strava app (which is highly likely) - the authorization will not work correctly. The user might be redirected back to Strava instead to my app.

So, the idea is that every app should have its own scheme. Hence, this property should be customizable.

I hope I managed to explain it better?

**Comment by BirdyF** [comment]
Thank you. I understand.
Yes there was a conflict (issue #32) with Strava app.
But since the version 1.2.1+51 it should be fixed because url scheme is now "stravaflutter" and not anymore "strava"
The bundlename in iOS is still "strava" but it should not interfere with strava app..

**Comment by etabakov** [comment]
Yes, so #32 will solve the case for conflict with a Strava app. But you can have a conflict between two other apps who are using the flutter_strava package for example. 

For many reasons I would like to have unique url scheme for my app to avoid all type of conflicts with other apps. See here for more information: https://developer.android.com/training/app-links/deep-linking#adding-filters

**Comment by BirdyF** [comment]
OK. But sorry I dont know how to add or parametrize url scheme (on iOS or Android).
If you know how to do it, you can a PR and I will check

**Comment by etabakov** [comment]
No worries, I will open PR in the next days. Thanks!
