### ISSUE TITLE
Example code with `getEffortsbySegmentId()` runs out Strava API request limit

### ISSUE THREAD

**Issue by gki** [dreampowder/strava_flutter#42]
# Problem
 I tried to run example code of this lib and when I tapped "Segments" button several times, Strava API started to return an error below.
```
{"message":"Rate Limit Exceeded","errors":[{"resource":"Application","field":"rate limit","code":"exceeded"}]}
```

Also, Strava web app shows the number of API requests are extremely high during 15min. (In 2nd graph, the number of requests are around 2500 during 15 min, although I've set up this Strava API just now!!)

<img width="965" alt="スクリーンショット 2020-08-15 16 20 42" src="https://user-images.githubusercontent.com/1529390/90307652-46989980-df13-11ea-815e-a241e44e435f.png">

As debugging result, a do-while loop in `SegmentEfforts#getEffortsbySegmentId()` seemed to did infinite loop.

# Suggestion
If this API will support retry capability, I recommend to have the default "max retry count”. Otherwise, the user of this library may runs out API request limit in very short time unexpectedly, like me.

**Comment by BirdyF** [comment]
Hi @gki 
Sorry for the trouble.
But it is mentioned in the header of this API SegmentEfforts#getEffortsbySegmentId()  that it is not working yet.
I will fix the problem as soon as I have the time.
