### ISSUE TITLE
Have a version of uploadActivity which accepts String (XML) or List<int> input instead of file name

### ISSUE THREAD

**Issue by MrCsabaToth** [dreampowder/strava_flutter#46]
When I upload I don't want the file to materialize but I'd like to upload it from memory. In such case I generate the TCX in memory. (Note that I also would like to upload TCX.gz instead of the larger uncompressed TCX. `uploadActivity` uses `http.MultipartFile.fromPath`. For in-memory text content there's `http.MultipartFile.fromString` and for gzip we could use `http.MultipartFile.fromBytes`. All what needs to be done that this file inclusion statement be factored out to the other two variants and the rest of the function can stay in a core function. This could also help with future tests.

**Comment by BirdyF** [comment]
Hi @MrCsabaToth 

I agree with you this will be a nice improvement.

**Comment by MrCsabaToth** [comment]
I implemented this but it caused so much code churn and API change (also related to rw_tcx as well) that I don't have a PR for this right now.
