### ISSUE TITLE
Upgrade shared_preferences dependency to 2.0.0

### ISSUE THREAD

**Issue by derrickstampede** [dreampowder/strava_flutter#52]
Hello, first is thank you for providing this package. But it's currently lagging when it comes to the latest packages specifically shared_preferences. And some of the packages I need are dependent on the latest shared_preferences version. Is there a chance you will update your package soon? :)

**Comment by johnsheehan** [comment]
I'm running into similar issue with url_launcher.

Thanks for the library!

**Comment by Jacek-Galla** [comment]
I created Pull request https://github.com/BirdyF/strava_flutter/pull/53

**Comment by BirdyF** [comment]
Hi @derrickstampede, @johnsheehan, @Jacek-Galla 
Sorry but currently I dont have the time (and the equipment) to work on it.
I should be able to do it not before mid-April.
 If there is anybody interested to maintain the repo I can transfer it.
