### ISSUE TITLE
Please upgrade the depedencies

### ISSUE THREAD

**Issue by yusmi25** [dreampowder/strava_flutter#58]
please upgrade the package, because the depedencies is too old
thanks. :D

**Comment by BirdyF** [comment]
Hi @yusmi25 I will try to do it next week but not sure yet.

**Comment by eoanodea** [comment]
I'm running into the same issue, is there any update on this? :)

**Comment by raja-karthik** [comment]
Please update the plugin.

**Comment by BirdyF** [comment]
Sorry @eoanodea @raja-karthik but I dont have anymore the time to work on this project and I now I have only one old Mac.
Is there anyone interested to take over Strava_flutter? I can do a transfer.

**Comment by haslinger** [comment]
Thanks for the heads up and thank you so much for writing and maintaining the library for a long time. I will look into it and come back to this issue with an answer.

**Comment by raja-karthik** [comment]
Thank you so much @haslinger . Come on. Folks. Please upgrade little bit earlier with null safety.
