### ISSUE TITLE
Anyone interested to take over strava_flutter?

### ISSUE THREAD

**Issue by BirdyF** [dreampowder/strava_flutter#60]
I don't have anymore the time to work on this project.
Is there anyone to take care of this project?

**Comment by dreampowder** [comment]
@BirdyF hello there, i'd like to spend some time in your project. I am already working on a project with strava integration anyway

**Comment by BirdyF** [comment]
Hi @dreampowder. Thanks. I will transfer the repo later today.

**Comment by BirdyF** [comment]
Done. 
You should have received the request to accept the transfer.
I hope to have to have some time end of this year to work on this project again.

**Comment by dreampowder** [comment]
Thanks so much for giving us a good headstart with strava api with flutter. I'll take good care of the project
