### ISSUE TITLE
pub.dev entry

### ISSUE THREAD

**Issue by dreampowder** [dreampowder/strava_flutter#65]
Hello @BirdyF , i am about to release a new version in few weeks and i wonder if you can give me publish access from pub.dev, or mark flutter_strava as "discontinued" so i can release with a new one (ofcourse by mentioning you)  while keeping pub.dev free from discontinued packages

**Comment by etabakov** [comment]
@BirdyF any update on this one? The package has been stuck for more than an year and I'd love not to have to refer to the github repo for updates.

**Comment by dreampowder** [comment]
I am considering to release this package as a new package. Looks like the @BirdyF doesn't use github anymore. What do you think?

**Comment by dreampowder** [comment]
published as a new package: 

https://pub.dev/packages/strava_client
