### ISSUE TITLE
"Request Failed" error on Strava app when I try to authorize

### ISSUE THREAD

**Issue by harkairt** [dreampowder/strava_flutter#72]
When I load the request url to browser
`https://www.strava.com/oauth/mobile/authorize?client_id=73709&redirect_uri=stravaflutter://redirect&response_type=code&approval_prompt=force&scope=read_all` 
 and click Authorize then I get a simple 302, and nothing else

![Screenshot_20211103-172453](https://user-images.githubusercontent.com/32367206/140101462-46e8ba05-ba2d-433c-b300-15e6f771b238.jpg)

**Comment by dreampowder** [comment]
hello, can you also share your androidmanifest.xml file please?

**Comment by harkairt** [comment]
This happens with the example app from this repo. I noticed it is missing the necessary information, even after adding them

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.example">
   <application
        android:label="example"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
              <action android:name="android.intent.action.VIEW" />  
              <category android:name="android.intent.category.DEFAULT" /> 
              <category android:name="android.intent.category.BROWSABLE" /> 
              <data android:scheme="stravaflutter" android:host="redirect" />    
              <data android:pathPattern="/.*" />   
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

regardless, to me it looks like an issue with Strava, but I am not sure

**Comment by dreampowder** [comment]
hello, please make following changes: 

```xml
<intent-filter>
              <action android:name="android.intent.action.VIEW" />  
              <category android:name="android.intent.category.DEFAULT" /> 
              <category android:name="android.intent.category.BROWSABLE" /> 
              <data android:scheme="stravaflutter"/>   
            </intent-filter>
`

and launchMode to 'singleInstance'

`
android:launchMode="singleInstance"
`

please tell me if it works so i can close this issue.

**Comment by dreampowder** [comment]
I am still working on the example project and documentation, so thanks for warning.

**Comment by harkairt** [comment]
Sadly it did not change anything. I get the same error

**Comment by supermnemonic** [comment]
> hello, please make following changes:
> 
> ```
> <intent-filter>
>               <action android:name="android.intent.action.VIEW" />  
>               <category android:name="android.intent.category.DEFAULT" /> 
>               <category android:name="android.intent.category.BROWSABLE" /> 
>               <data android:scheme="stravaflutter"/>   
>             </intent-filter>
> `
> 
> and launchMode to 'singleInstance'
> 
> `
> android:launchMode="singleInstance"
> `
> 
> please tell me if it works so i can close this issue.
> ```

will that be okay by removing the host?
