### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by yusmi25** [dreampowder/strava_flutter#73]
hello, thanks to @dreampowder @BirdyF to make this package, It's very usefull when working with strava API so far, but any plan to upgrade this package, because the Dependencies is too old.
Thanks 👍 💯

**Comment by dreampowder** [comment]
hi @yusmi25, if you are using this package from pub.dev dependency, then yeah you are using the old repository. 
sadly @BirdyF transferred this account to me but forgot to transfer pub.dev rights to publish this package as a new version. 

The whole package has been refactored and almost rewritten from scratch. ( so no backwards compability ) . I am thinking about releasing this package with a new name over pub.dev

**Comment by yusmi25** [comment]
I get it. to get the latest source code of a package, I must get from github not from pub.dev right ?
but It's good idea if @BirdyF forgot to transfer the pub.dev you can releasing this package with a new pub.dev account (by mention the creator), because only this package can helping to intergate with Strava API 👍

**Comment by dreampowder** [comment]
yeah, your pubspec.yaml shuold look like this: 

`  strava_flutter:
    git:
      url: https://github.com/dreampowder/strava_flutter
      ref: 12ce5c8be5d11a250dc3f175d3171b9f24abb3bd`
