### ISSUE TITLE
model detailed athlete

### ISSUE THREAD

**Issue by tczesiu** [dreampowder/strava_flutter#76]
In the DetailedAthlete.fromJson there is a code 

clubs: List<SummaryClub>.from(json["clubs"].map((x) => SummaryClub.fromJson(x))),

It should be updated to do the null check, like this

clubs: json["clubs"] == null
              ? <SummaryClub>[]
              : List<SummaryClub>.from(
                  json["clubs"].map((x) => SummaryClub.fromJson(x))),

**Comment by dreampowder** [comment]
thanks for your feedback.
