### ISSUE TITLE
getLoggedInAthleteActivities in Readme deprecated?

### ISSUE THREAD

**Issue by haslinger** [dreampowder/strava_flutter#77]
A huge 'THANK YOU' for taking over the project, @dreampowder !

I guess, the readme is currently out of date, as getLoggedInAthleteActivities to give an example is no longer in the code?
I'm trying to follow the example code, but I don't see, where and how activities can be fetched.

No hurries, I'm just trying to update in a development branch, to be able to test along with the current developments of the package. :-)

**Comment by dreampowder** [comment]
hİ @haslinger thanks for your kind words, I am just returning my favor to the open source community :)

as for your question, I guess the relevant api is located in;

```dart
client.activities.listLoggedInAthleteActivities(..)
```


I tried to group all endpoints into their own repositories as stated on strata api page located in here: 

[Strava api page](https://developers.strava.com/docs/reference/#api-Activities-getLoggedInAthleteActivities)
