### ISSUE TITLE
LateInitializationError: Field 'secret' has already been initialized.

### ISSUE THREAD

**Issue by nikhilmufc7** [dreampowder/strava_flutter#80]
Issue with StravaClient

This happens when the Strava page is not in a one page application, if the user navigates to the page where strava initialization happens -> goes back -> opens the strava page again, I am encountering this issue.

This does not happen on navigating the first time as the initialization is done successfully. But on pop the initialization data is still stored in SessionManager.

Is there any way we can clear the initialization or reinitalize the Strava Client on popping the view.

**Comment by dreampowder** [comment]
Hi @nikhilmufc7 that looks like an important thing to fix, i will try to fix this asap but i am currently quite busy with my projects. So i'd love to have a pr about this if you can

**Comment by dreampowder** [comment]
hi there, sorry for late response due to my workload in there days. 
i removed the "final" modifier from these values, you shuold be able to update those values from now on.
