### ISSUE TITLE
pub.dev dependency doens't work

### ISSUE THREAD

**Issue by InSomniaMoon** [dreampowder/strava_flutter#83]
the dependency can't be added from pub.dev beacause the version works with cupertino isons 0.1.2, whereas flutter now works with cupertino_icons 1.0.2 and higher.

Solution : I downloaded the github project and added it into a "package" folder a the root of my project, and added this in the dependencies in pubsec.yaml : 
strava_flutter:
    path: packages/strava_flutter

**Comment by dreampowder** [comment]
You can use GitHub links form pub.dev like this:

https://stackoverflow.com/questions/54022704/how-to-add-a-package-from-github-in-flutter
