### ISSUE TITLE
"Request Failed"error when authenticate

### ISSUE THREAD

**Issue by yusmi25** [dreampowder/strava_flutter#84]
I get Problem When I load the request using the example
![Screenshot_2022-04-08-10-48-05-153_com strava](https://user-images.githubusercontent.com/60766202/162360692-b259962f-cce6-48e7-8c90-ae9b1bf51afa.jpg)

my Android Manifest : 

`
```
...
<intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="stravaflutter" android:host="redirect" />
              <data android:pathPattern="/.*" />
            </intent-filter>
        </activity>
```
`
On Strava API "Authorization Callback Domain" ="redirect"
Thank You.

**Comment by yusmi25** [comment]
I edit the manifest :
```
<intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="stravaflutter" android:host="redirect" />
            </intent-filter>
        </activity>
```
but when I click Authorize, the app automatic restart and the authentication failed

**Comment by yusmi25** [comment]
> I edit the manifest :
> 
> ```
> <intent-filter>
>               <action android:name="android.intent.action.MAIN" />
>               <category android:name="android.intent.category.LAUNCHER" />
>             </intent-filter>
>             <intent-filter>
>               <action android:name="android.intent.action.VIEW" />
>               <category android:name="android.intent.category.DEFAULT" />
>               <category android:name="android.intent.category.BROWSABLE" />
>               <data android:scheme="stravaflutter" android:host="redirect" />
>             </intent-filter>
>         </activity>
> ```
> 
> but when I click Authorize, the app automatic restart and the authentication failed

update: this error on android 10

**Comment by seanradford** [comment]
Does anyone have an answer to this issue?

Thanks.

**Comment by dreampowder** [comment]
this should be fixed with the latest updates,  please pull from the latest commit again
