### ISSUE TITLE
"strava" links are blocked

### ISSUE THREAD

**Issue by yusmi25** [dreampowder/strava_flutter#85]
I'm using example code, and get the issue  when I click Authorize and get an error
![Screenshot_20220531-094950_Chrome](https://user-images.githubusercontent.com/60766202/171083675-f3b8466a-e721-4af2-ab56-af83db0d7659.jpg)
Thanks 👍

**Comment by dreampowder** [comment]
Did you register the url scheme in info.plist or intent in the manifest.xml of android?
